spring:
  application:
    name: file-security-transmission-tool

authentication-result:
  succeed: "Authentication Passed"
  failed: "Authentication Failed"

client:
  serverHost: 127.0.0.1
  serverPort: 9000
  connectionTimeout: 5000
  authTimeoutSeconds: 10
  ackTimeoutSeconds: 10

node:
  device-id: device-default
  auto-connect: false

app:
  local-storage:
    transfer-history-path: ${TRANSFER_HISTORY_PATH:${user.home}/.file-security-transmission/transfer-history.json} #本机传输记录文件的保存路径
  crypto-key:
    private-key-path: ${PRIVATE_KEY_PATH:${user.home}/.file-security-transmission/identity_private.pkcs8}
    public-key-path: ${PUBLIC_KEY_PATH:${user.home}/.file-security-transmission/identity_public.x509}
  redis-state:
    challenge-ttl-seconds: 300
    online-session-ttl-seconds: 120
    transfer-route-ttl-seconds: 86400


server:
  address: localhost
  port: 8080
  tcp:
    enabled: true
    bind-host: 0.0.0.0
    bind-port: 9000

crypto-service:
  address: 127.0.0.1
  port: 9080


transfer:
  chunk-size-bytes: 1048576 #1mb
  receive-dir: downloads
