spring:
  application:
    name: file-security-transmission-tool

authentication-result:
  succeed: "Authentication Passed"
  failed: "Authentication Failed"

client:
  server-host: 127.0.0.1
  server-port: 9000

server:
  address: localhost
  port: 8080
  tcp:
    bind-host: 0.0.0.0
    bind-port: 9000

crypto-service:
  address: 127.0.0.1
  port: 9080
